### PR TITLE
Reagent example

### PR DESCRIPTION
**Pull request by crisptrutski**
refs #1 

Basic example integrating with Reagent, showing two (naive) ratom-to-ref binding techniques.

Also wrote a version using wraps before noticing they're not released yet (:cry:) - thought best to demo against stable. Seems simple enough that it'll just work (see commented code) - and definitely looks more elegant (kills off the mutate! helper functions in regular case)

@verma just used the reagent template here, not sure if you want to strip it down to something more minimal like the Om example (just a cljs file in a named build, and dev-dependencies)

@gadfly361 this is my first time using reagent so please give any pointers on sloppiness - or feel free to jump in and  plushify.

Or if you'd like to see an example of something more specific, let me know!

### CODE REVIEW

**Comment by gadfly361** [comment]
Oh awesome, thanks for making a reagent example!!  When I cloned repo, example ran after `lein install` without problems.

Feel free to add a pani recipe to [reagent-cookbook](https://github.com/reagent-project/reagent-cookbook) if you'd like, otherwise I'll make a link to the reagent example here once it is pulled in :)

**Comment by verma** [comment]
This is nice! I think a minimal example would be great too, I'll try to find time to make one since I want to play with reagent as well :)

**Comment by crisptrutski** [comment]
@gadfly361 maybe wait till Reagent 0.5.0? The solution here, "always read from ratom, always write to pani" is not really modular. Also we're about to overhaul the API here.

Keen to add the stand-alone example to your cookbook once above is sorted, adding better comments and a README too - the example in this repo will be paired back to live in the main project and have less dependencies ;)

**Comment by gadfly361** [comment]
Good call, definitely makes sense to wait for a little more stability on both ends!

**Pull request merged**
