### PR TITLE
Bundle Firebase via CLJSJS package

### LINKED ISSUE #22: cljsjs/firebase
Hey, just a heads up:
I just pushed [cljsjs/firebase](https://github.com/cljsjs/packages/tree/master/firebase) which your library could depend on using the new :foreign-libs features in Clojurescript `0.0-2727`.

It's version 2.1.2.

### PR DESCRIPTION
**Pull request by crisptrutski**
@martinklepsch thanks for the nudge - really appreciate the work you're doing with CLJSJS, something along these lines was very necessary!

Unfortunately switching over has not been plain sailing, owing both coming back to this project after a period of neglect, and my limited understanding of CLJS compilation, providing details below.

Closes #22

### CODE REVIEW

**Comment by crisptrutski** [comment]
#### Issues I ran into:

1. When using :whitespace compilation, the emitted js for the "test" profile fails due to duplicate definition of goog modules (eg. `Error: Namespace "goog.string" already declared.`).

  Switching to :advanced mode gets around this, but slows down auto-test feedback loop. Why are dependencies being repeated and is there a way to fix this and continue using :whitespace compilation with the :foreign-libs dependency?

2. The externs file's hoisting of variables does not seem to sit well with the compiler, basically get warnings like:

```
WARNING: f~/.m2/repository/cljsjs/firebase/2.1.2-0/firebase-2.1.2-0.jar!/cljsjs/common/firebase.ext.js:9: WARNING - accessing name Firebase in externs has no effect. Perhaps you forgot to add a var keyword?
Firebase = (function() {
^
 ```

The warning sounds like this is actually breaking the definition, so not sure why the externs file is structured this way (perhaps compatible with another version of Closure compiler?).

Haven't had a chance to yet - but assume you've used this package successfully in a project?

@verma assuming you're onboard with this direction, let me know otherwise.

Not related to CLJS but complicating matters for me, the ClojureScript test suite seems to be stalling when I run, even from master. Will bisect later to see if this is due to code change or potentially something environmental for me - could you confirm whether `lein auto-test` is working on master for you?

It is probably also time to get onto the latest JVM Firebase library too (`[com.firebase/firebase-client-jvm "2.1.2"] is available but we use "1.1.1"`)

**Comment by martinklepsch** [comment]
> When using :whitespace compilation, the emitted js for the "test" profile fails due to duplicate definition of goog modules (eg. Error: Namespace "goog.string" already declared.).

For some reason `firebase-debug.js`, which is included when not using `:advanced` seems to redefine `goog.provide`. Not sure why, but I'll try to figure it out. I guess as a short term solution we might just use the minified file for both modes.

> The externs file's hoisting of variables does not seem to sit well with the compiler

Fixed that in master. Will cut `2.1.2-1` when I figured the `goog.provide` thing out.

**Comment by crisptrutski** [comment]
Thanks!

**Comment by martinklepsch** [comment]
I just released `[cljsjs/firebase "2.1.2-1"]` which should fix the problems you mentioned.
The `good.provide` errors were due to `firebase-debug.js` redefining some `goog` namespaces already present via Clojurescript. For now I figured it's best to only use the minified version.

**Comment by crisptrutski** [comment]
@martinklepsch works perfectly
@verma merge if you're satisfied

**Comment by verma** [comment]
Awesome! Thanks @crisptrutski @martinklepsch :)

**Pull request merged**
